/* Reference data for the label heuristics.
 *
 * Nothing here needs to be exhaustive: every guess lands in an editable field,
 * so the cost of a miss is one correction, and the cost of a wrong confident
 * match is the same. The lists cover what actually turns up on bottles.
 */

/** Grape names, with the colour each implies when the label does not say. */
export const VARIETALS = [
  // Red
  ['Cabernet Sauvignon', 'Red'], ['Cabernet Franc', 'Red'], ['Merlot', 'Red'],
  ['Pinot Noir', 'Red'], ['Syrah', 'Red'], ['Shiraz', 'Red'], ['Grenache', 'Red'],
  ['Garnacha', 'Red'], ['Mourvèdre', 'Red'], ['Monastrell', 'Red'], ['Carignan', 'Red'],
  ['Cariñena', 'Red'], ['Cinsault', 'Red'], ['Malbec', 'Red'], ['Petit Verdot', 'Red'],
  ['Tannat', 'Red'], ['Zinfandel', 'Red'], ['Primitivo', 'Red'], ['Sangiovese', 'Red'],
  ['Nebbiolo', 'Red'], ['Barbera', 'Red'], ['Dolcetto', 'Red'], ['Corvina', 'Red'],
  ['Rondinella', 'Red'], ['Molinara', 'Red'], ['Montepulciano', 'Red'],
  ['Aglianico', 'Red'], ["Nero d'Avola", 'Red'], ['Negroamaro', 'Red'],
  ['Lambrusco', 'Red'], ['Tempranillo', 'Red'], ['Mencía', 'Red'], ['Bobal', 'Red'],
  ['Touriga Nacional', 'Red'], ['Touriga Franca', 'Red'], ['Tinta Roriz', 'Red'],
  ['Baga', 'Red'], ['Pinotage', 'Red'], ['Carmenère', 'Red'], ['Gamay', 'Red'],
  ['Blaufränkisch', 'Red'], ['Zweigelt', 'Red'], ['Saperavi', 'Red'],
  ['Xinomavro', 'Red'], ['Agiorgitiko', 'Red'], ['Plavac Mali', 'Red'],
  ['Refosco', 'Red'], ['Schiava', 'Red'], ['Teroldego', 'Red'], ['Lagrein', 'Red'],
  ['Sagrantino', 'Red'], ['Cannonau', 'Red'], ['Frappato', 'Red'], ['Bonarda', 'Red'],
  ['Trousseau', 'Red'], ['Poulsard', 'Red'], ['Mondeuse', 'Red'], ['Counoise', 'Red'],
  ['Alicante Bouschet', 'Red'], ['Graciano', 'Red'], ['Mazuelo', 'Red'],
  ['Castelão', 'Red'], ['Trincadeira', 'Red'], ['Alfrocheiro', 'Red'],

  // White
  ['Chardonnay', 'White'], ['Sauvignon Blanc', 'White'], ['Riesling', 'White'],
  ['Pinot Gris', 'White'], ['Pinot Grigio', 'White'], ['Pinot Blanc', 'White'],
  ['Gewürztraminer', 'White'], ['Muscat', 'White'], ['Moscato', 'White'],
  ['Viognier', 'White'], ['Marsanne', 'White'], ['Roussanne', 'White'],
  ['Chenin Blanc', 'White'], ['Sémillon', 'White'], ['Albariño', 'White'],
  ['Alvarinho', 'White'], ['Verdejo', 'White'], ['Godello', 'White'],
  ['Viura', 'White'], ['Macabeo', 'White'], ['Xarel·lo', 'White'],
  ['Parellada', 'White'], ['Grüner Veltliner', 'White'], ['Silvaner', 'White'],
  ['Müller-Thurgau', 'White'], ['Vermentino', 'White'], ['Trebbiano', 'White'],
  ['Garganega', 'White'], ['Falanghina', 'White'], ['Fiano', 'White'],
  ['Greco', 'White'], ['Verdicchio', 'White'], ['Cortese', 'White'],
  ['Arneis', 'White'], ['Ribolla Gialla', 'White'], ['Friulano', 'White'],
  ['Malvasia', 'White'], ['Assyrtiko', 'White'], ['Moschofilero', 'White'],
  ['Furmint', 'White'], ['Rkatsiteli', 'White'], ['Torrontés', 'White'],
  ['Colombard', 'White'], ['Melon de Bourgogne', 'White'], ['Picpoul', 'White'],
  ['Clairette', 'White'], ['Bourboulenc', 'White'], ['Aligoté', 'White'],
  ['Savagnin', 'White'], ['Petite Arvine', 'White'], ['Koshu', 'White'],
  ['Grillo', 'White'], ['Catarratto', 'White'], ['Carricante', 'White'],
  ['Pecorino', 'White'], ['Vernaccia', 'White'], ['Scheurebe', 'White'],
  ['Kerner', 'White'], ['Chasselas', 'White'], ['Loureiro', 'White'],
  ['Arinto', 'White'], ['Encruzado', 'White'], ['Antão Vaz', 'White'],
];

/**
 * Appellations, each with the country and region it implies.
 * Longest match wins, so "Chianti Classico" beats "Chianti".
 * Pure grape names are deliberately absent — they belong to VARIETALS.
 */
export const APPELLATIONS = [
  // France — Bordeaux
  ['Margaux', 'France', 'Bordeaux'], ['Pauillac', 'France', 'Bordeaux'],
  ['Saint-Julien', 'France', 'Bordeaux'], ['Saint-Estèphe', 'France', 'Bordeaux'],
  ['Pessac-Léognan', 'France', 'Bordeaux'], ['Graves', 'France', 'Bordeaux'],
  ['Saint-Émilion', 'France', 'Bordeaux'], ['Pomerol', 'France', 'Bordeaux'],
  ['Fronsac', 'France', 'Bordeaux'], ['Sauternes', 'France', 'Bordeaux'],
  ['Barsac', 'France', 'Bordeaux'], ['Haut-Médoc', 'France', 'Bordeaux'],
  ['Médoc', 'France', 'Bordeaux'], ['Listrac-Médoc', 'France', 'Bordeaux'],
  ['Moulis-en-Médoc', 'France', 'Bordeaux'], ['Bordeaux Supérieur', 'France', 'Bordeaux'],
  ['Bordeaux', 'France', 'Bordeaux'],

  // France — Burgundy and Beaujolais
  ['Chablis', 'France', 'Bourgogne'], ['Meursault', 'France', 'Bourgogne'],
  ['Puligny-Montrachet', 'France', 'Bourgogne'], ['Chassagne-Montrachet', 'France', 'Bourgogne'],
  ['Gevrey-Chambertin', 'France', 'Bourgogne'], ['Nuits-Saint-Georges', 'France', 'Bourgogne'],
  ['Vosne-Romanée', 'France', 'Bourgogne'], ['Chambolle-Musigny', 'France', 'Bourgogne'],
  ['Morey-Saint-Denis', 'France', 'Bourgogne'], ['Pommard', 'France', 'Bourgogne'],
  ['Volnay', 'France', 'Bourgogne'], ['Savigny-lès-Beaune', 'France', 'Bourgogne'],
  ['Aloxe-Corton', 'France', 'Bourgogne'], ['Corton-Charlemagne', 'France', 'Bourgogne'],
  ['Clos de la Roche', 'France', 'Bourgogne'], ['Clos de Vougeot', 'France', 'Bourgogne'],
  ['Échezeaux', 'France', 'Bourgogne'], ['Richebourg', 'France', 'Bourgogne'],
  ['Romanée-Conti', 'France', 'Bourgogne'], ['Montrachet', 'France', 'Bourgogne'],
  ['Chambertin', 'France', 'Bourgogne'], ['Musigny', 'France', 'Bourgogne'],
  ['Pouilly-Fuissé', 'France', 'Bourgogne'], ['Saint-Véran', 'France', 'Bourgogne'],
  ['Mercurey', 'France', 'Bourgogne'], ['Rully', 'France', 'Bourgogne'],
  ['Givry', 'France', 'Bourgogne'], ['Montagny', 'France', 'Bourgogne'],
  ['Mâcon-Villages', 'France', 'Bourgogne'], ['Mâcon', 'France', 'Bourgogne'],
  ['Beaune', 'France', 'Bourgogne'], ['Bourgogne', 'France', 'Bourgogne'],
  ['Moulin-à-Vent', 'France', 'Beaujolais'], ['Côte de Brouilly', 'France', 'Beaujolais'],
  ['Brouilly', 'France', 'Beaujolais'], ['Morgon', 'France', 'Beaujolais'],
  ['Fleurie', 'France', 'Beaujolais'], ['Juliénas', 'France', 'Beaujolais'],
  ['Chénas', 'France', 'Beaujolais'], ['Chiroubles', 'France', 'Beaujolais'],
  ['Régnié', 'France', 'Beaujolais'], ['Saint-Amour', 'France', 'Beaujolais'],
  ['Beaujolais', 'France', 'Beaujolais'],

  // France — Rhône, Loire, and the rest
  ['Châteauneuf-du-Pape', 'France', 'Rhône'], ['Côtes du Rhône', 'France', 'Rhône'],
  ['Gigondas', 'France', 'Rhône'], ['Vacqueyras', 'France', 'Rhône'],
  ['Rasteau', 'France', 'Rhône'], ['Cairanne', 'France', 'Rhône'],
  ['Lirac', 'France', 'Rhône'], ['Tavel', 'France', 'Rhône'],
  ['Crozes-Hermitage', 'France', 'Rhône'], ['Hermitage', 'France', 'Rhône'],
  ['Cornas', 'France', 'Rhône'], ['Saint-Joseph', 'France', 'Rhône'],
  ['Côte-Rôtie', 'France', 'Rhône'], ['Condrieu', 'France', 'Rhône'],
  ['Sancerre', 'France', 'Loire'], ['Pouilly-Fumé', 'France', 'Loire'],
  ['Vouvray', 'France', 'Loire'], ['Chinon', 'France', 'Loire'],
  ['Bourgueil', 'France', 'Loire'], ['Saumur-Champigny', 'France', 'Loire'],
  ['Saumur', 'France', 'Loire'], ['Savennières', 'France', 'Loire'],
  ['Muscadet', 'France', 'Loire'], ['Quincy', 'France', 'Loire'],
  ['Menetou-Salon', 'France', 'Loire'], ['Montlouis', 'France', 'Loire'],
  ['Coteaux du Layon', 'France', 'Loire'], ['Anjou', 'France', 'Loire'],
  ['Champagne', 'France', 'Champagne'], ['Alsace', 'France', 'Alsace'],
  ['Bandol', 'France', 'Provence'], ['Cassis', 'France', 'Provence'],
  ['Côtes de Provence', 'France', 'Provence'], ['Bellet', 'France', 'Provence'],
  ['Corbières', 'France', 'Languedoc'], ['Minervois', 'France', 'Languedoc'],
  ['Faugères', 'France', 'Languedoc'], ['Saint-Chinian', 'France', 'Languedoc'],
  ['Picpoul de Pinet', 'France', 'Languedoc'], ['Pic Saint-Loup', 'France', 'Languedoc'],
  ['Fitou', 'France', 'Languedoc'], ['Collioure', 'France', 'Roussillon'],
  ['Banyuls', 'France', 'Roussillon'], ['Maury', 'France', 'Roussillon'],
  ['Rivesaltes', 'France', 'Roussillon'], ['Cahors', 'France', 'Sud-Ouest'],
  ['Madiran', 'France', 'Sud-Ouest'], ['Jurançon', 'France', 'Sud-Ouest'],
  ['Gaillac', 'France', 'Sud-Ouest'], ['Monbazillac', 'France', 'Sud-Ouest'],
  ['Bergerac', 'France', 'Sud-Ouest'], ['Irouléguy', 'France', 'Sud-Ouest'],
  ['Château-Chalon', 'France', 'Jura'], ['Côtes du Jura', 'France', 'Jura'],
  ['Arbois', 'France', 'Jura'], ['Patrimonio', 'France', 'Corse'],

  // Italy
  ['Barolo', 'Italy', 'Piemonte'], ['Barbaresco', 'Italy', 'Piemonte'],
  ["Barbera d'Alba", 'Italy', 'Piemonte'], ["Barbera d'Asti", 'Italy', 'Piemonte'],
  ["Dolcetto d'Alba", 'Italy', 'Piemonte'], ['Langhe', 'Italy', 'Piemonte'],
  ['Roero', 'Italy', 'Piemonte'], ['Gavi', 'Italy', 'Piemonte'],
  ["Moscato d'Asti", 'Italy', 'Piemonte'], ['Asti', 'Italy', 'Piemonte'],
  ['Franciacorta', 'Italy', 'Lombardia'], ['Valtellina', 'Italy', 'Lombardia'],
  ['Amarone della Valpolicella', 'Italy', 'Veneto'],
  ['Valpolicella Ripasso', 'Italy', 'Veneto'], ['Valpolicella', 'Italy', 'Veneto'],
  ['Soave', 'Italy', 'Veneto'], ['Bardolino', 'Italy', 'Veneto'],
  ['Conegliano Valdobbiadene', 'Italy', 'Veneto'], ['Prosecco', 'Italy', 'Veneto'],
  ['Lugana', 'Italy', 'Veneto'], ['Alto Adige', 'Italy', 'Trentino-Alto Adige'],
  ['Trentino', 'Italy', 'Trentino-Alto Adige'], ['Collio', 'Italy', 'Friuli'],
  ['Colli Orientali', 'Italy', 'Friuli'], ['Chianti Classico', 'Italy', 'Toscana'],
  ['Chianti', 'Italy', 'Toscana'], ['Brunello di Montalcino', 'Italy', 'Toscana'],
  ['Rosso di Montalcino', 'Italy', 'Toscana'],
  ['Vino Nobile di Montepulciano', 'Italy', 'Toscana'],
  ['Bolgheri', 'Italy', 'Toscana'], ['Carmignano', 'Italy', 'Toscana'],
  ['Vernaccia di San Gimignano', 'Italy', 'Toscana'],
  ['Morellino di Scansano', 'Italy', 'Toscana'], ['Maremma', 'Italy', 'Toscana'],
  ['Montefalco Sagrantino', 'Italy', 'Umbria'], ['Orvieto', 'Italy', 'Umbria'],
  ['Verdicchio dei Castelli di Jesi', 'Italy', 'Marche'],
  ["Montepulciano d'Abruzzo", 'Italy', 'Abruzzo'], ['Taurasi', 'Italy', 'Campania'],
  ['Greco di Tufo', 'Italy', 'Campania'], ['Fiano di Avellino', 'Italy', 'Campania'],
  ['Aglianico del Vulture', 'Italy', 'Basilicata'],
  ['Primitivo di Manduria', 'Italy', 'Puglia'], ['Salice Salentino', 'Italy', 'Puglia'],
  ['Cerasuolo di Vittoria', 'Italy', 'Sicilia'], ['Etna', 'Italy', 'Sicilia'],
  ['Marsala', 'Italy', 'Sicilia'], ['Cannonau di Sardegna', 'Italy', 'Sardegna'],
  ['Vermentino di Gallura', 'Italy', 'Sardegna'],

  // Spain and Portugal
  ['Rioja', 'Spain', 'Rioja'], ['Ribera del Duero', 'Spain', 'Castilla y León'],
  ['Rueda', 'Spain', 'Castilla y León'], ['Toro', 'Spain', 'Castilla y León'],
  ['Bierzo', 'Spain', 'Castilla y León'], ['Priorat', 'Spain', 'Catalunya'],
  ['Montsant', 'Spain', 'Catalunya'], ['Penedès', 'Spain', 'Catalunya'],
  ['Empordà', 'Spain', 'Catalunya'], ['Terra Alta', 'Spain', 'Catalunya'],
  ['Costers del Segre', 'Spain', 'Catalunya'], ['Cava', 'Spain', 'Catalunya'],
  ['Rías Baixas', 'Spain', 'Galicia'], ['Ribeiro', 'Spain', 'Galicia'],
  ['Valdeorras', 'Spain', 'Galicia'], ['Ribeira Sacra', 'Spain', 'Galicia'],
  ['Jerez', 'Spain', 'Andalucía'], ['Montilla-Moriles', 'Spain', 'Andalucía'],
  ['Jumilla', 'Spain', 'Murcia'], ['Yecla', 'Spain', 'Murcia'],
  ['Navarra', 'Spain', 'Navarra'], ['Somontano', 'Spain', 'Aragón'],
  ['Campo de Borja', 'Spain', 'Aragón'], ['Calatayud', 'Spain', 'Aragón'],
  ['Utiel-Requena', 'Spain', 'Valencia'], ['La Mancha', 'Spain', 'Castilla-La Mancha'],
  ['Valdepeñas', 'Spain', 'Castilla-La Mancha'],
  ['Douro', 'Portugal', 'Douro'], ['Porto', 'Portugal', 'Douro'],
  ['Dão', 'Portugal', 'Dão'], ['Bairrada', 'Portugal', 'Bairrada'],
  ['Vinho Verde', 'Portugal', 'Minho'], ['Alentejo', 'Portugal', 'Alentejo'],
  ['Setúbal', 'Portugal', 'Setúbal'], ['Madeira', 'Portugal', 'Madeira'],

  // Germany and Austria
  ['Mosel', 'Germany', 'Mosel'], ['Rheingau', 'Germany', 'Rheingau'],
  ['Rheinhessen', 'Germany', 'Rheinhessen'], ['Pfalz', 'Germany', 'Pfalz'],
  ['Nahe', 'Germany', 'Nahe'], ['Baden', 'Germany', 'Baden'],
  ['Württemberg', 'Germany', 'Württemberg'], ['Franken', 'Germany', 'Franken'],
  ['Ahr', 'Germany', 'Ahr'], ['Wachau', 'Austria', 'Niederösterreich'],
  ['Kremstal', 'Austria', 'Niederösterreich'], ['Kamptal', 'Austria', 'Niederösterreich'],
  ['Weinviertel', 'Austria', 'Niederösterreich'], ['Carnuntum', 'Austria', 'Niederösterreich'],
  ['Neusiedlersee', 'Austria', 'Burgenland'], ['Leithaberg', 'Austria', 'Burgenland'],
  ['Mittelburgenland', 'Austria', 'Burgenland'], ['Burgenland', 'Austria', 'Burgenland'],
  ['Südsteiermark', 'Austria', 'Steiermark'],

  // New World
  ['Napa Valley', 'USA', 'California'], ['Sonoma Coast', 'USA', 'California'],
  ['Russian River Valley', 'USA', 'California'], ['Alexander Valley', 'USA', 'California'],
  ['Dry Creek Valley', 'USA', 'California'], ['Stags Leap District', 'USA', 'California'],
  ['Howell Mountain', 'USA', 'California'], ['Oakville', 'USA', 'California'],
  ['Rutherford', 'USA', 'California'], ['Paso Robles', 'USA', 'California'],
  ['Sta. Rita Hills', 'USA', 'California'], ['Santa Lucia Highlands', 'USA', 'California'],
  ['Santa Barbara', 'USA', 'California'], ['Anderson Valley', 'USA', 'California'],
  ['Carneros', 'USA', 'California'], ['Mendocino', 'USA', 'California'],
  ['Lodi', 'USA', 'California'], ['Willamette Valley', 'USA', 'Oregon'],
  ['Dundee Hills', 'USA', 'Oregon'], ['Columbia Valley', 'USA', 'Washington'],
  ['Walla Walla Valley', 'USA', 'Washington'], ['Yakima Valley', 'USA', 'Washington'],
  ['Red Mountain', 'USA', 'Washington'], ['Finger Lakes', 'USA', 'New York'],
  ['Marlborough', 'New Zealand', 'Marlborough'],
  ['Central Otago', 'New Zealand', 'Central Otago'],
  ["Hawke's Bay", 'New Zealand', "Hawke's Bay"],
  ['Martinborough', 'New Zealand', 'Wairarapa'],
  ['Barossa Valley', 'Australia', 'South Australia'],
  ['McLaren Vale', 'Australia', 'South Australia'],
  ['Clare Valley', 'Australia', 'South Australia'],
  ['Eden Valley', 'Australia', 'South Australia'],
  ['Adelaide Hills', 'Australia', 'South Australia'],
  ['Coonawarra', 'Australia', 'South Australia'],
  ['Yarra Valley', 'Australia', 'Victoria'],
  ['Margaret River', 'Australia', 'Western Australia'],
  ['Hunter Valley', 'Australia', 'New South Wales'],
  ['Tasmania', 'Australia', 'Tasmania'],
  ['Stellenbosch', 'South Africa', 'Western Cape'],
  ['Swartland', 'South Africa', 'Western Cape'],
  ['Franschhoek', 'South Africa', 'Western Cape'],
  ['Walker Bay', 'South Africa', 'Western Cape'],
  ['Constantia', 'South Africa', 'Western Cape'],
  ['Paarl', 'South Africa', 'Western Cape'],
  ['Uco Valley', 'Argentina', 'Mendoza'], ['Mendoza', 'Argentina', 'Mendoza'],
  ['Salta', 'Argentina', 'Salta'], ['Patagonia', 'Argentina', 'Patagonia'],
  ['Maipo Valley', 'Chile', 'Valle del Maipo'],
  ['Colchagua', 'Chile', 'Valle de Colchagua'],
  ['Casablanca Valley', 'Chile', 'Valle de Casablanca'],
  ['Aconcagua', 'Chile', 'Aconcagua'], ['Limarí', 'Chile', 'Limarí'],
  ['Tokaj', 'Hungary', 'Tokaj'], ['Eger', 'Hungary', 'Eger'],
  ['Villány', 'Hungary', 'Villány'], ['Santorini', 'Greece', 'Santorini'],
  ['Nemea', 'Greece', 'Peloponnese'], ['Naoussa', 'Greece', 'Macedonia'],
];

/** Countries as printed on labels, with the English name to record. */
export const COUNTRIES = [
  ['France', 'France'], ['Italy', 'Italy'], ['Italia', 'Italy'],
  ['Spain', 'Spain'], ['España', 'Spain'], ['Espana', 'Spain'],
  ['Portugal', 'Portugal'], ['Germany', 'Germany'], ['Deutschland', 'Germany'],
  ['Austria', 'Austria'], ['Österreich', 'Austria'], ['Australia', 'Australia'],
  ['New Zealand', 'New Zealand'], ['South Africa', 'South Africa'],
  ['Argentina', 'Argentina'], ['Chile', 'Chile'], ['United States', 'USA'],
  ['USA', 'USA'], ['California', 'USA'], ['Greece', 'Greece'],
  ['Hungary', 'Hungary'], ['Romania', 'Romania'], ['Georgia', 'Georgia'],
  ['Switzerland', 'Switzerland'], ['Suisse', 'Switzerland'], ['Lebanon', 'Lebanon'],
  ['Israel', 'Israel'], ['Uruguay', 'Uruguay'], ['Brazil', 'Brazil'],
  ['Canada', 'Canada'], ['England', 'England'], ['Slovenia', 'Slovenia'],
  ['Croatia', 'Croatia'], ['Japan', 'Japan'],
];

/** Words that name a wine's type, checked in this order — the first hit wins. */
export const TYPE_WORDS = [
  ['Sparkling', ['sparkling', 'spumante', 'cremant', 'champagne', 'cava', 'sekt',
    'prosecco', 'franciacorta', 'metodo classico', 'methode traditionnelle',
    'blanc de blancs', 'blanc de noirs', 'brut', 'extra dry', 'pet nat']],
  ['Fortified', ['porto', 'port wine', 'sherry', 'jerez', 'madeira', 'marsala',
    'vin doux naturel', 'oloroso', 'amontillado', 'fino', 'manzanilla',
    'pedro ximenez', 'tawny', 'ruby']],
  ['Dessert', ['sauternes', 'moelleux', 'passito', 'late harvest', 'vendanges tardives',
    'beerenauslese', 'trockenbeerenauslese', 'eiswein', 'ice wine', 'dolce',
    'selection de grains nobles', 'vin de paille', 'recioto']],
  ['Rosé', ['rose wine', 'vin rose', 'rosato', 'rosado', 'rosé', 'rose']],
  ['White', ['white wine', 'vino bianco', 'vin blanc', 'vino blanco', 'weisswein',
    'vinho branco', 'bianco', 'blanc', 'blanco', 'branco', 'weiss']],
  ['Red', ['red wine', 'vino rosso', 'vin rouge', 'vino tinto', 'rotwein',
    'vinho tinto', 'rosso', 'rouge', 'tinto', 'tinta', 'rot']],
];

/** Lines that are packaging boilerplate rather than anything worth recording. */
export const NOISE_PATTERNS = [
  /\b\d{1,2}[.,]?\d*\s*%\s*(vol|alc)/i,
  /\balc(ohol)?\b.*\bvol\b/i,
  /\b\d{2,4}\s?(ml|cl|l)\b/i,
  /\bcontains?\s+sulfites?\b/i,
  /\bsulphites?\b/i,
  /\bgovernment\s+warning\b/i,
  /\bsurgeon\s+general\b/i,
  /\bimported\s+by\b/i,
  /\bdistributed\s+by\b/i,
  /\bproduct\s+of\b/i,
  /\bproduce\s+of\b/i,
  /\bmis\s+en\s+bouteille\b/i,
  /\bestate\s+bottled\b/i,
  /\bbottled\s+by\b/i,
  /\bimbottigliato\b/i,
  /\bembotellado\b/i,
  /\berzeugerabf(ü|u)llung\b/i,
  /\bgrand\s+vin\b/i,
  /\bvin\s+de\s+france\b/i,
  /\bappellation\b.*\b(contr[oô]l[ée]e|prot[ée]g[ée]e)\b/i,
  /\bdenominazione\s+di\s+origine\b/i,
  /\bdenominaci[oó]n\s+de\s+origen\b/i,
  /\bwine\s+of\s+origin\b/i,
  /^\d{6,}$/,
  /^[\d\s.,%-]+$/,
];

/** Openings that mark a line as the producer's name with high confidence.
 *  Matched only when at least one more word follows, so a bare "Champagne"
 *  stays an appellation. */
export const PRODUCER_PREFIXES = [
  'château', 'chateau', 'domaine', 'domaines', 'bodega', 'bodegas', 'weingut',
  'tenuta', 'tenute', 'quinta', 'cantina', 'cantine', 'azienda agricola',
  'azienda', 'podere', 'poderi', 'castello', 'viña', 'vina', 'viñedos',
  'marqués de', 'marques de', 'maison', 'fattoria', 'masseria', 'herdade',
  'schloss', 'clos', 'famille', 'família', 'familia', 'cave', 'caves',
  'champagne', 'casa', "ca'", 'weinhaus', 'weingärtner', 'winzer',
];

/** Closings that do the same job at the end of a name: "Ridge Vineyards". */
export const PRODUCER_SUFFIXES = [
  'winery', 'wineries', 'vineyards', 'vineyard', 'cellars', 'cellar',
  'estate', 'estates', 'wines', 'wine co', 'brothers', 'family wines',
];

/** Single-vineyard markers. */
export const VINEYARD_PATTERNS = [
  /\bvigneto\s+(.+)$/i,
  /\bvigna\s+(.+)$/i,
  /\bvi[ñn]edo\s+(.+)$/i,
  /^(.+?)\s+vineyard$/i,
  /\bsingle\s+vineyard\s+(.+)$/i,
];

/** Words that precede a year that is not the vintage. */
export const NON_VINTAGE_MARKERS = [
  'est', 'estd', 'established', 'since', 'founded', 'fondee', 'fondata',
  'fundada', 'gegrundet', 'anno', 'depuis', 'dal', 'desde', 'seit', 'aoc',
];
